version: '3.1'

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - "6000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: data
  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080